apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: olmv1-metrics-cert
spec:
  secretName: olmv1-cert
  dnsNames:
    - operator-controller-metrics-service.olmv1-system.svc
    - operator-controller-metrics-service.olmv1-system.svc.cluster.local
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: olmv1-ca
    kind: ClusterIssuer
    group: cert-manager.io
