name: catalogd-e2e

on:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches:
    - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run E2e
        run: make test-catalogd-e2e
  upgrade-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run the upgrade e2e test
        working-directory: catalogd
        run: make test-upgrade-e2e
