on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-title:
    runs-on: ubuntu-latest
    name: Verify PR title
    steps:
      - name: Verify PR title
        id: get_title
        run: echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
      - name: Run Check
        id: check_title
        run: |
          ./hack/test/pr-title.sh "${{ env.title }}"
